### ISSUE TITLE
[BUG] Bi-directional connection results in an exception

### ISSUE THREAD

**Issue by mksbamford** [Unity-Technologies/UnityRenderStreaming#548] opened 2021-10-11 16:19 UTC
**Describe the bug**
Attempting a Bi-directional connection (PC-Mac) results in an exception.
Similarly, iPhone to iPad also fails using the hardware encoder.

StackTrace:
AssertionException: Assertion failure. Values are not equal.
Expected: Stable == HaveLocalOffer
[polite-Unity.RenderStreaming.PeerConnection] answered
UnityEngine.Assertions.Assert.Fail (System.String message, System.String userMessage) (at <a555715ef291462eb190c2c939543f55>:0)
UnityEngine.Assertions.Assert.AreEqual[T] (T expected, T actual, System.String message, System.Collections.Generic.IEqualityComparer`1[T] comparer) (at <a555715ef291462eb190c2c939543f55>:0)
UnityEngine.Assertions.Assert.AreEqual[T] (T expected, T actual, System.String message) (at <a555715ef291462eb190c2c939543f55>:0)
Unity.RenderStreaming.RenderStreamingInternal+<GotAnswerCoroutine>d__63.MoveNext () (at Assets/com.unity.renderstreaming/Runtime/Scripts/RenderStreamingInternal.cs:503)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <a555715ef291462eb190c2c939543f55>:0)

**To Reproduce**
Open the Unity Editor on a Mac and a PC
Attempt to make a video call over websockets using the software encoder
Observe error

**Expected behavior**
Each device sees the others camera.

**Environment (please complete the following information):**
 - OS: Windows 10, macOS 11.2
 - Unity Version 2019.4.19f1
 - Package version latest develop branch with WebRTC 2.4.0-exp.4

**Comment by karasusan** [comment] 2021-10-18 01:56
Did you upgrade the WebRTC package version of Unity Render Streaming?
We will test it the situation you said.

**Comment by mksbamford** [comment] 2021-10-18 12:32
I used WebRTC 2.4.0-exp.4

**Comment by karasusan** [comment] 2021-11-09 02:37
memo: URS-332

**Comment by karasusan** [comment] 2021-11-26 08:20
@mksbamford
I checked your issue and result below.
- iOS (Hardware) - iOS (Hardware): OK
- iOS (Hardware) - macOS (Software): macOS does not render iOS camera.
- iOS (Hardware) - macOS (Hardware): OK
- iOS (Hardware) - Windows (Software) windows does not render iOS camera.
- iOS (Hardware) - Windows (Hardware) windows does not render iOS camera.
- Mac (Hardware) - Windows (Hardware) windows does not render macOS camera.

There is a table of supporting Hardware codec. 
https://docs.unity3d.com/Packages/com.unity.webrtc@2.4/manual/index.html

Usually, same codecs need to be selected on sender and receiver. Additionally, windows is not supported hardware decoder yet, so the bidirectional sample doesn't work using HW codec on windows.

**Comment by mksbamford** [comment] 2021-11-26 12:46
The difference might be that I am using AR on iOS, could this cause issues?

**Comment by karasusan** [comment] 2021-11-27 00:17
@mksbamford
That may just be true.
Are you testing with AR sample?

**Comment by mksbamford** [comment] 2021-11-27 00:27
No I’m testing in an app

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by kannan-xiao4** [comment] 2021-12-14 03:10
@mksbamford 
At the time of QA with the latest package (3.1.0-exp.2), no problem was found with the combination of AR and HWA.
Can you check with the latest version?
I want to know a more about the reproduction conditions. thanks

**Comment by mksbamford** [comment] 2022-01-04 16:41
@kannan-xiao4 

Demo Project: https://drive.google.com/file/d/1h2gNMldGj7FWNve4-z-Y3-qcAB8dATQD/view?usp=sharing

Load the Test/Scenes/RenderStreaming scene on 2 devices,
On device A, choose Host.
Wait a few seconds.
On device B, choose Join.
Observe issues mentioned previously.

**Comment by karasusan** [comment] 2022-01-05 03:11
@mksbamford 
Thanks. I requested you to allow to access the demo project.

**Comment by mksbamford** [comment] 2022-01-05 09:01
@karasusan Done

**Comment by kannan-xiao4** [comment] 2022-02-09 09:49
@mksbamford 

I checked your project, but I didn't get the above AssertError in my environment.
However, the Join-side camera is not rendering on the Host-side.
I check using `Tests/Scenes/Renderstreaming.unity` .

Here are my test results only error occoured combination, the format is Host (encoding) --Client (encoding)
My mac is using Intel chipset.

macOS (Software)-Windows (Software): macOS correctly renders Windows camera. Windows does not render macOS camera. But No AssertionError
Windows (Software)-macOS (Software): Windows correctly renders macOS camera. macOS does not render Windows camera. But No AssertionError

I think this is due to the implementation of `MultiConnection.cs` used in this scene.
Perhaps this implementation is based on `Broadcast.cs`.
If you want to send and receive video in both directions, please refer to `SingleConnection.cs` and implement it.

**Comment by kannan-xiao4** [comment] 2022-02-14 04:30
@mksbamford 
In the current receiving component, the receiving target can be set only by `ConnectionId`.
Therefore, when there are multiple targets, the video cannot be rendered correctly on the host side.
As a countermeasure for that, we are planning to make it possible to specify Label in StreamingReceveBase.
I made the Issue. https://github.com/Unity-Technologies/UnityRenderStreaming/issues/641

I couldn't reproduce the error (AssertError ), so can I close this issue?

**Comment by mksbamford** [comment] 2022-02-14 15:16
@kannan-xiao4 
I'm not sure your suggestion will solve the problem because:
There isn't multiple targets there is only 1 for each?
It is the client side that isn't receiving video, not the host side?
I'm still getting the assertion error on the client side

**Comment by kannan-xiao4** [comment] 2022-02-15 08:54
@mksbamford 
Sorry, I mistake and I reproduce your error.

1.
And I found the Assersion error occurred by implimentation about `MultiConnection.cs`
On `OnCreateConnection` process, no need call `SendOffer` because OnNegotiationNeeded invoked by SetupConnection process. 
If delete this process, No error occurs.

```MultiConnection.cs
...

        public void OnCreatedConnection(SignalingEventData data)
        {
            var connectionId = data.connectionId;
            SetupConnection(data);
            // SendOffer(connectionId); no need send offer.
        }
...
```

2.
I checked offer/answer SDP.
There is no problem with the SDP sent from the guest (join) side.
However, there is a problem with the answer SDP from the host side.
On the host side, only that there is a receive track is transmitted by SDP. Does not include send track in answer SDP.
You need to add a track in the OnOffer process of the MultiConnection class.

```MultiConnection.cs
...

        public void OnOffer(SignalingEventData data)
        {
            var connectionId = data.connectionId;

            if (connectionIds.Contains(connectionId))
            {
                Debug.Log($"Already answered this connectionId : {data.connectionId}");
                return;
            }

            connectionIds.Add(connectionId);

            foreach (var source in streams.OfType<IStreamSender>())
            {
                AddSender(data.connectionId, source);
            }
            SendAnswer(connectionId);
        }
...
```

Please try both code. thanks!

**Comment by mksbamford** [comment] 2022-02-15 13:56
Removing the SendOffer does stop the Assert occurring
However, AddSender in OnOffer stops the video working on both sides.

**Comment by kannan-xiao4** [comment] 2022-02-18 02:06
@mksbamford 
I have reproduced it, so I will investigate it again.

memo: URS-412

**Comment by kannan-xiao4** [comment] 2022-07-25 06:53
@mksbamford 
Hi, I checked this problem on latest develop branch.
In the latest develop branch, you can send and receive video correctly in both directions.
However, the implementation of MultiConnection needs to be as follows.

```
using System.Collections.Generic;
using System.Linq;
using Unity.RenderStreaming;
using Unity.WebRTC;
using UnityEngine;

namespace ExtendView.RenderStreaming
{
    public class MultiConnection : SignalingHandlerBase,
        IOfferHandler, IAddChannelHandler, IDisconnectHandler, IDeletedConnectionHandler,
        ICreatedConnectionHandler, IAddReceiverHandler//IFoundConnectionHandler
    {
        [SerializeField]
        private List<Component> streams = new List<Component>();

        private List<string> connectionIds = new List<string>();

        public void AddComponent(Component component)
        {
            streams.Add(component);
        }

        public void RemoveComponent(Component component)
        {
            streams.Remove(component);
        }

        public override void CreateConnection(string connectionId)
        {
            connectionIds.Add(connectionId);
            base.CreateConnection(connectionId);
        }

        public void OnDeletedConnection(SignalingEventData eventData)
        {
            Disconnect(eventData.connectionId);
        }

        public void OnDisconnect(SignalingEventData eventData)
        {
            Disconnect(eventData.connectionId);
        }

        public override void DeleteConnection(string connectionId)
        {
            Disconnect(connectionId);
            base.DeleteConnection(connectionId);
        }

        private void Disconnect(string connectionId)
        {
            if (!connectionIds.Contains(connectionId))
                return;
            connectionIds.Remove(connectionId);

            foreach (var sender in streams.OfType<IStreamSender>())
            {
                RemoveSender(connectionId, sender);
            }
            foreach (var receiver in streams.OfType<IStreamReceiver>())
            {
                RemoveReceiver(connectionId, receiver);
            }
            foreach (var channel in streams.OfType<IDataChannel>())
            {
                RemoveChannel(connectionId, channel);
            }
        }

        public void OnCreatedConnection(SignalingEventData data)
        {
            SetupConnection(data);
        }

        void SetupConnection(SignalingEventData data)
        {
            var connectionId = data.connectionId;

            foreach (var sender in streams.OfType<IStreamSender>())
            {
                AddSender(connectionId, sender);
            }
            foreach (var channel in streams.OfType<IDataChannel>().Where(c => c.IsLocal))
            {
                AddChannel(connectionId, channel);
            }
        }

        public void OnOffer(SignalingEventData data)
        {
            var connectionId = data.connectionId;

            if (connectionIds.Contains(connectionId))
            {
                Debug.Log($"Already answered this connectionId : {data.connectionId}");
                return;
            }

            connectionIds.Add(connectionId);
            foreach (var source in streams.OfType<IStreamSender>())
            {
                AddSender(data.connectionId, source);
            }
            foreach (var channel in streams.OfType<IDataChannel>().Where(c => c.IsLocal))
            {
                AddChannel(connectionId, channel);
            }
            SendAnswer(connectionId);
        }

        public void OnAddReceiver(SignalingEventData data)
        {
            var receiver = streams.OfType<IStreamReceiver>()
                .FirstOrDefault((r =>
                    r.Track == null && r.Kind == data.receiver.Track.Kind && data.receiver.Track.Enabled));
            receiver?.SetReceiver(data.connectionId, data.receiver);
        }

        public void OnAddChannel(SignalingEventData data)
        {
            var channel = streams.OfType<IDataChannel>().
                FirstOrDefault(r => r.Channel == null && !r.IsLocal);
            channel?.SetChannel(data.connectionId, data.channel);
        }
    }
}

```
Please try it in your environment

I changed implementation on below project.
https://drive.google.com/file/d/1l-x9ZQ7WQZIwnoHUvzouX3ALE2iK_wOd/view?usp=sharing

**Comment by mb-virtualretail** [comment] 2022-08-03 19:23
@karasusan thanks, I was able to make this work, however, I think its worth noting, when the CameraStreamSender has no depthbuffer, in the sample this was causing the rotating cube to disappear (it looks to me that the camera is being rendered without a depth buffer and thus the skybox is rendered on top of the cube)

**Comment by mksbamford** [comment] 2022-08-03 19:23
@karasusan thanks, I was able to make this work, however, I think its worth noting, when the CameraStreamSender has no depthbuffer, in the sample this was causing the rotating cube to disappear (it looks to me that the camera is being rendered without a depth buffer and thus the skybox is rendered on top of the cube)

**Comment by karasusan** [comment] 2022-08-08 01:32
@mksbamford
Ah, sorry for that. You need the depth buffer to render correctly.
I relieved hear that you fixed the issue. If you have no problem, I will close the ticket. Thanks.

**Closed** 2022-08-23 05:01 UTC
Labels: bug, stabled, issued
