### ISSUE TITLE
[BUG] iOS 13.5 doesn't connect to webserver (Safari and Chrome)

### ISSUE THREAD

**Issue by SilvioDuy** [Unity-Technologies/UnityRenderStreaming#310] opened 2020-07-02 09:39 UTC
Hello!
I created a project and followed all the steps. Everything works fine on other desktop and Android devices (after adding firewall rules for Unity Editor). The only device that cannot connect to the webserver is my iPhone 11 (iOS 13.5.1). I tried to download Chrome (even though Safari is supported) but nothing happens when I hit the play button on the page, no errors at all, it seems that it just doesn't connect to the server.

 - Server OS: Windows 10
 - Device OS: iOS 13.5.1
 - Browser Chrome and Safari
 - Unity Version 2019.4.0f1
 - Package version 2.0.2

**Comment by karasusan** [comment] 2020-07-14 05:11
Have you ever seen the FAQ document?
I guess the issue caused by the restriction for the security reason on iOS .
https://docs.unity3d.com/Packages/com.unity.renderstreaming@2.0/manual/en/faq.html#web-app-doesnt-run-on-safari-browser

**Comment by karasusan** [comment] 2020-08-24 07:25
@SilvioDuy 
Have you resolved your issue?
If you have no problem, I will close this ticket.

**Comment by karasusan** [comment] 2020-08-28 06:36
I closed the issue.
Please reopen if you have not resolved yet.

**Closed by karasusan** 2020-08-28 06:36 UTC
Labels: bug
