### ISSUE TITLE
Use android chrome is appear WEBRTC error when PC is work well

### ISSUE THREAD

**Issue by Leemu0822** [Unity-Technologies/UnityRenderStreaming#154] opened 2019-09-23 09:55 UTC

**Comment by sindharta** [comment] 2019-09-24 07:40
Are you saying that:
1. Renderstreaming works fine for you on PC
2. Renderstreaming does not work for you on Chrome on your Android device ?

**Comment by Leemu0822** [comment] 2019-09-24 09:44
Yes,The Unity Editor is pause and appear er RTC error immediately  When I use Chrome on my Android device and connect the PC server

**Comment by karasusan** [comment] 2019-09-24 12:46
Could you attach a error log?

**Comment by emanonhero** [comment] 2019-09-25 03:12
unity editor:
Network Error: Unity.WebRTC.RTCError
UnityEngine.Debug:LogError(Object)
Unity.RenderStreaming.<Answer>d__20:MoveNext() (at Assets/Scripts/RenderStreaming.cs:183)
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)

Chrome:

video-player.js:155 Uncaught (in promise) DOMException: Failed to execute 'addIceCandidate' on 'RTCPeerConnection': Error processing ICE candidate
 async function (async)   
 loopGetCandidate @ video-player.js:142 
 sendOffer @ video-player.js:116 
 async function (async)   
 sendOffer @ video-player.js:114 
 setupConnection @ video-player.js:102 
 async function (async)   
 setupConnection @ video-player.js:90 
 setupVideoPlayer @ app.js:99 
 onClickPlayButton @ app.js:40

**Comment by sindharta** [comment] 2019-09-25 04:20
Just confirming, have you made sure that you have started your webserver and put the shown IP into the "Url Signaling" field in the RenderStreaming component in Unity ?

**Comment by Leemu0822** [comment] 2019-09-25 04:26
Yes，I confirm, It is work well on two PCS

**Comment by sindharta** [comment] 2019-09-25 06:51
Can you please let us know the version of Chrome on your Android ?

**Comment by Leemu0822** [comment] 2019-09-25 06:54
Chrome 76.0.3809.132

**Comment by emanonhero** [comment] 2019-09-26 01:47
> Yes，I confirm, It is work well on two PCS

你挺厉害了，我测试了一下只能在node.js服务器的本机运行，我是用run.bat运行服务器的。请问你是怎么弄得，可以在另外的PC上正常显示。

**Comment by sindharta** [comment] 2019-09-26 02:02
@Leemu0822 I am afraid we can't reproduce this bug. 
Is it possible for you to update to the latest Chrome and try it again ?

**Comment by Leemu0822** [comment] 2019-09-26 02:11
> @Leemu0822 I am afraid we can't reproduce this bug.
> Is it possible for you to update to the latest Chrome and try it again ?
OK, I will try it as much as possible and thanks for your answer


> @Leemu0822 I am afraid we can't reproduce this bug.
> Is it possible for you to update to the latest Chrome and try it again ?

ok, I will try it as much

**Comment by Leemu0822** [comment] 2019-09-26 02:13
@sindharta  OK, I will try it as much as possible and thanks for your answer

**Comment by Leemu0822** [comment] 2019-09-26 02:15
@emanonhero 我是直接在webserver.exe目录，启动命令行，输入命令: webserver.exe -p 8800  启动的，8800是自己自定义的端口，可以随意填

**Comment by YhPopulus** [comment] 2019-09-26 04:07
FireFox Browser(Android/iPhone) : 

Network Error: Unity.WebRTC.RTCError
UnityEngine.Debug:LogError(Object)
Unity.RenderStreaming.<Answer>d__20:MoveNext() (at Assets/Scripts/RenderStreaming.cs:183)
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)

**Comment by sindharta** [comment] 2019-09-26 04:28
FireFox is not supported at the moment.
See **Supported Browsers** on https://github.com/Unity-Technologies/UnityRenderStreaming

**Comment by emanonhero** [comment] 2019-09-26 09:04
@Leemu0822  我是git clone的项目 里面没有webserver.exe，请问webserver.exe是哪里来的？

**Comment by Leemu0822** [comment] 2019-09-26 09:06
@emanonhero  你看readme的教程文档，有相关的介绍

**Comment by sindharta** [comment] 2019-11-26 05:43
Closing due to non-activity.

@Leemu0822 If you still have this error while using the latest Chrome on your Android device , please reopen this issue.

**Closed** 2019-11-26 05:43 UTC
Labels: bug

**Comment by mehdikhadir** [comment] 2020-03-23 14:23
Hello,
I also have such an issue when trying to connect on Chrome/Android. That's what the Unity console tells me:

Network Error: Unity.WebRTC.RTCError
UnityEngine.Debug:LogError(Object)
Unity.RenderStreaming.<Answer>d__20:MoveNext() (at Assets/Scripts/RenderStreaming.cs:183)
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)

The connection works fine with Chrome/MacOS though. I'm using the preview release version 1.2.3
Do you have any idea where the issue might come from?
Thanks in advance.

**Comment by sindharta** [comment] 2020-03-26 01:21
@mehdikhadir Please open a new issue for this, and attach a screenshot together with the logs from Unity and the WebServer if possible

**Comment by mehdikhadir** [comment] 2020-03-30 08:24
Hello @sindharta, thanks for your answer.
I opened a new issue: https://github.com/Unity-Technologies/UnityRenderStreaming/issues/252
