### ISSUE TITLE
[BUG] Tracks are not removed after disconnecting peers

### ISSUE THREAD

**Issue by gushenjie** [Unity-Technologies/UnityRenderStreaming#462] opened 2021-04-20 06:00 UTC
When I refresh the webpage, the CPU will keep accumulating

**Comment by karasusan** [comment] 2021-04-20 06:38
Could I have more information about your issue?

**Comment by gushenjie** [comment] 2021-04-20 06:46
First, I run the webapp to start the service. I use the websocket mode and the public mode. Then I run the WebBrowserInput application. After the connection is successful, I open the index.html under the videoplayer module in the webapp. At this time, I open the win10 computer performance view. At the beginning, my CPU usage was 38%. When I refreshed the videoplayer index.html, the CPU value became more than 50%. I continued to refresh and it kept improving. In the end, my CPU reached 100%, and I didn’t refresh it at this time, but his usage rate never dropped.

**Comment by gushenjie** [comment] 2021-04-21 01:25
UnityRenderStreaming 3.0.1 Version

**Comment by gushenjie** [comment] 2021-04-22 10:35
> Could I have more information about your issue?
First, I run the webapp to start the service. I use the websocket mode and the public mode. Then I run the WebBrowserInput application. After the connection is successful, I open the index.html under the videoplayer module in the webapp. At this time, I open the win10 computer performance view. At the beginning, my CPU usage was 38%. When I refreshed the videoplayer index.html, the CPU value became more than 50%. I continued to refresh and it kept improving. In the end, my CPU reached 100%, and I didn’t refresh it at this time, but his usage rate never dropped.

UnityRenderStreaming 3.0.1 Version

**Comment by karasusan** [comment] 2021-04-24 01:50
I got it.
I need to check `Render Stremaing` component settings in the inspector window.
Can you take a screenshot?

**Comment by gushenjie** [comment] 2021-04-25 05:09
Except for changing the default http request method to websocket, the other configurations have not changed
![image](https://user-images.githubusercontent.com/10531802/115981581-65cde780-a5c7-11eb-9caa-2d233561c318.png)

**Comment by gushenjie** [comment] 2021-04-28 01:57
![image](https://user-images.githubusercontent.com/10531802/116334050-28579d00-a807-11eb-9d90-717740d09738.png)
In this case, I only open the application of webbrowserinput

![image](https://user-images.githubusercontent.com/10531802/116334431-c9deee80-a807-11eb-92d7-758228b83f35.png)
In this case, I only opened an HTML web page, videoplayer / index. HTML

![image](https://user-images.githubusercontent.com/10531802/116334603-1296a780-a808-11eb-925d-ad893ce9436a.png)
I refreshed the webpage several times. After a period of time, the CPU utilization rate is still relatively high. Is there something that hasn't been released?

**Comment by karasusan** [comment] 2021-05-06 06:32
Thanks, I will try to reproduce it.

**Comment by karasusan** [comment] 2021-06-04 00:31
@gushenjie
Hi, which process is the highest CPU usage in this situation?
Thanks.

**Comment by dhr0118** [comment] 2021-06-21 03:31
@karasusan 
Hi, I had a similar problem. When I open a webpage and run UnityEditor just on my pc, it's fine. But when I run UnityEditor on my own computer, I open a webpage on another computer in the LAN. After a period of time, the CPU utilization up to 100%, then my computer crashed..
I use the httpSignaling mode, also UnityRenderStreaming 3.0.1 Version.

**Comment by dhr0118** [comment] 2021-07-10 09:31
Version 3.0.x and 3.1 had this problem. When I back to 2.x version, the problem is gone.

**Comment by dhr0118** [comment] 2021-07-16 01:55
> I noticed the same problem. I found that in Broadcast.cs `AddTrack` is called in `OnOffer` but `RemoveTrack` is never called. So the video/audio tracks are probably never removed and keep on using resources. I added `RemoveTrack` in `Disconnect` like so and the problem was resolved for me:
> 
> ```cs
> private void Disconnect(string connectionId)
>   {
>       if (!connectionIds.Contains(connectionId))
>           return;
>       connectionIds.Remove(connectionId);
> 
>       foreach (var source in streams.OfType<IStreamSource>())
>       {
>           RemoveTrack(connectionId, source.Track);
>           source.SetSender(connectionId, null);
>       }
>       foreach (var receiver in streams.OfType<IStreamReceiver>())
>       {
>           receiver.SetReceiver(connectionId, null);
>       }
>       foreach (var channel in streams.OfType<IDataChannel>())
>       {
>           channel.SetChannel(connectionId, null);
>       }
>   }
> ```
> 
> #506 is probably the same issue

It works! Thank you!

**Comment by gushenjie** [comment] 2021-07-20 09:30
> > I noticed the same problem. I found that in Broadcast.cs `AddTrack` is called in `OnOffer` but `RemoveTrack` is never called. So the video/audio tracks are probably never removed and keep on using resources. I added `RemoveTrack` in `Disconnect` like so and the problem was resolved for me:
> > ```cs
> > private void Disconnect(string connectionId)
> >   {
> >       if (!connectionIds.Contains(connectionId))
> >           return;
> >       connectionIds.Remove(connectionId);
> > 
> >       foreach (var source in streams.OfType<IStreamSource>())
> >       {
> >           RemoveTrack(connectionId, source.Track);
> >           source.SetSender(connectionId, null);
> >       }
> >       foreach (var receiver in streams.OfType<IStreamReceiver>())
> >       {
> >           receiver.SetReceiver(connectionId, null);
> >       }
> >       foreach (var channel in streams.OfType<IDataChannel>())
> >       {
> >           channel.SetChannel(connectionId, null);
> >       }
> >   }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > #506 is probably the same issue
> 
> It works! Thank you!

我没有找到RemoveTrack实现方法,是否可以共享出来？

**Comment by gushenjie** [comment] 2021-07-20 09:30
> I noticed the same problem. I found that in Broadcast.cs `AddTrack` is called in `OnOffer` but `RemoveTrack` is never called. So the video/audio tracks are probably never removed and keep on using resources. I added `RemoveTrack` in `Disconnect` like so and the problem was resolved for me:
> 
> ```cs
> private void Disconnect(string connectionId)
>   {
>       if (!connectionIds.Contains(connectionId))
>           return;
>       connectionIds.Remove(connectionId);
> 
>       foreach (var source in streams.OfType<IStreamSource>())
>       {
>           RemoveTrack(connectionId, source.Track);
>           source.SetSender(connectionId, null);
>       }
>       foreach (var receiver in streams.OfType<IStreamReceiver>())
>       {
>           receiver.SetReceiver(connectionId, null);
>       }
>       foreach (var channel in streams.OfType<IDataChannel>())
>       {
>           channel.SetChannel(connectionId, null);
>       }
>   }
> ```
> 
> #506 is probably the same issue

I haven't found a removetrack implementation. Can I share it?

**Comment by gushenjie** [comment] 2021-07-20 09:31
> > I noticed the same problem. I found that in Broadcast.cs `AddTrack` is called in `OnOffer` but `RemoveTrack` is never called. So the video/audio tracks are probably never removed and keep on using resources. I added `RemoveTrack` in `Disconnect` like so and the problem was resolved for me:
> > ```cs
> > private void Disconnect(string connectionId)
> >   {
> >       if (!connectionIds.Contains(connectionId))
> >           return;
> >       connectionIds.Remove(connectionId);
> > 
> >       foreach (var source in streams.OfType<IStreamSource>())
> >       {
> >           RemoveTrack(connectionId, source.Track);
> >           source.SetSender(connectionId, null);
> >       }
> >       foreach (var receiver in streams.OfType<IStreamReceiver>())
> >       {
> >           receiver.SetReceiver(connectionId, null);
> >       }
> >       foreach (var channel in streams.OfType<IDataChannel>())
> >       {
> >           channel.SetChannel(connectionId, null);
> >       }
> >   }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > #506 is probably the same issue
> 
> It works! Thank you!

I haven't found a removetrack implementation. Can I share it?

**Comment by pilzinho** [comment] 2021-07-20 13:45
Hi! I don't really understand your last post. If you are having trouble with my solution, make sure you have the source code of the Render Streaming package added to your project (downloaded from Github). You cannot change the code when you have imported the package via the Package Manager like it says in the documentation.
You will find the Broadcast.cs script in the subfolder 'com.unity.renderstreaming\Runtime\Scripts\'. In this script you can exchange the method Disconnect() with the one that I posted.

**Comment by gushenjie** [comment] 2021-07-20 14:52
Did you write removetrack? If so, the specific implementation content of the following method is provided



发自我的iPhone


------------------ Original ------------------
From: pilzinho ***@***.***&gt;
Date: Tue,Jul 20,2021 10:05 PM
To: Unity-Technologies/UnityRenderStreaming ***@***.***&gt;
Cc: gushenjie ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [Unity-Technologies/UnityRenderStreaming] [BUG] CPU BUG (#462)

**Comment by gushenjie** [comment] 2021-07-21 08:58
> I noticed the same problem. I found that in Broadcast.cs `AddTrack` is called in `OnOffer` but `RemoveTrack` is never called. So the video/audio tracks are probably never removed and keep on using resources. I added `RemoveTrack` in `Disconnect` like so and the problem was resolved for me:
> 
> ```cs
> private void Disconnect(string connectionId)
>   {
>       if (!connectionIds.Contains(connectionId))
>           return;
>       connectionIds.Remove(connectionId);
> 
>       foreach (var source in streams.OfType<IStreamSource>())
>       {
>           RemoveTrack(connectionId, source.Track);
>           source.SetSender(connectionId, null);
>       }
>       foreach (var receiver in streams.OfType<IStreamReceiver>())
>       {
>           receiver.SetReceiver(connectionId, null);
>       }
>       foreach (var channel in streams.OfType<IDataChannel>())
>       {
>           channel.SetChannel(connectionId, null);
>       }
>   }
> ```
> 
> #506 is probably the same issue

I'll rewrite the disconnect method in your way, open it on the web page after running, and it can load normally. After refreshing the web page, the unity program will block, and the unity editor will flash back later. The version I use is rendersteeeam3.0.0, webrtc 2.3.3

![image](https://user-images.githubusercontent.com/10531802/126461471-dd346d89-c4e1-45ff-aa5d-f55df3e913b9.png)

**Comment by gushenjie** [comment] 2021-07-21 10:22
It seems that hdrp template does not have the problem of repeated page refresh and CPU full? I didn't add the removetrack method

**Comment by gushenjie** [comment] 2021-07-21 10:27
h264 hareware encoding mode

**Comment by pilzinho** [comment] 2021-07-21 12:44
I'm sorry that it doesn't work for you. Is there a difference for you when you use software or hardware encoding? I'm currently using software encoding. You could also try updating the packages if this is possible for you. I'm using Render Streaming 3.1.0-exp.1 and WebRTC 2.4.0-exp.3.

**Comment by pilzinho** [comment] 2021-07-21 14:09
It works for me with hardware encoding as well

**Comment by gushenjie** [comment] 2021-07-22 05:45
> It works for me with hardware encoding as well

thank u , I upgrade software version to  solve this question

**Comment by pilzinho** [comment] 2021-07-22 12:20
I made a [forum post](https://forum.unity.com/threads/webrtc-renderstreaming-code-improvements.1145162/#post-7351925) with this and other changes I made. Maybe there's something else in there that's useful for you.

**Comment by karasusan** [comment] 2021-11-09 02:15
URS-316

**Comment by karasusan** [comment] 2021-11-16 11:16
I made a draft #581, this fix is for the issue.

**Comment by karasusan** [comment] 2021-11-22 05:08
@gushenjie
Fixed this issue and will release new version soon.

**Comment by karasusan** [comment] 2021-12-03 09:19
@gushenjie
@pilzinho
Released the new version contains the fix of this issue. 
I will close the issue if there is no problem. thanks.

**Closed** 2021-12-11 00:45 UTC
Labels: bug, waiting for release, issued
