### ISSUE TITLE
[REQUEST]Send a signal to mobile browser to open touch keyboard

### ISSUE THREAD

**Issue by Yuuon** [Unity-Technologies/UnityRenderStreaming#309] opened 2020-06-29 06:49 UTC
**Is your feature request related to a problem? Please describe.**
We're adding webRTC to our product, which is a online virtual 3D society. To login the game, there are two input fields for ID and password(We also have in-game chat so it's quite important, but first of first, we need to get the user login the game).
Now I've dealt with the input field interact issue, so from a remote PC/Mac, you can input text into the input fields. It works fine.
However, when accessing the webRTC contents via a mobile phone's browser(i.e., Android Chrome), I found the touch keyboard of mobile couldn't be triggered, since the browser doesn't think there is an "EditText" content in page(because it's a whole video element).

**Describe the solution you'd like**
I think the best solution is let the browser call the system IME as a normal input text field is focused in a normal web page.
I tried to use SendCantidate() for it but I have no idea about which and how to form a signal.

**Describe alternatives you've considered**
Anything which can send message from Unity, the RTC server side, to the remote browser. If it's too hard to imitate the mobile system event trigger, then use the web function to solve it. For example, add a JavaScript function in the viewer page, which shows a HTML input text field with a confirm button(and a cancel button if needed) when received a signal from the server(so if it's a HTML input text field, the browser should automatic call the system IME when it is focused), and that signal should be sent when a Unity Input field is focused from server. For muilt-user situation, only the user triggered the input field will receive the response. When the confirm button besides the HTML input text field clicked, transfer those text contents back to Unity, and fill them into the targeted Unity input field.

**Comment by karasusan** [comment] 2020-08-24 05:40
I am not sure the detail of your issue, but I think the issue is not caused by Render Streaming.
Currently we do not have a plan to make user management features to this package.

**Comment by doctorpangloss** [comment] 2020-11-29 19:02
On mobile you can't make a keyboard appear without a user-initiated action on a supported `input` element. Nothing - autofocus, `.focus()`, etc. - no technique can work around this.

This is by design by the browser vendors, this limitation mitigates security attacks that attempt to spoof iOS and Android system and OAuth password prompts.

**Comment by karasusan** [comment] 2022-01-25 03:01
@Yuuon
Hi, I guess your issue is that wanting IME support on browser, is it right?

**Comment by doctorpangloss** [comment] 2022-01-25 05:34
I think you have to make an onscreen keyboard inside Unity, that's what I do.

**Comment by kannan-xiao4** [comment] 2022-02-08 02:46
@doctorpangloss 
There are currently no plans to implement OnScreen Keyboard on Unity Side.

How do you currently implement input from a mobile browser?

**Comment by kannan-xiao4** [comment] 2022-02-22 02:46
@doctorpangloss 
Have you any questions?
If nothing, we will close this ticket.

**Closed** 2022-03-01 02:43 UTC
Labels: enhancement, stabled
