### ISSUE TITLE
[BUG] Unable to Send and Receive Audio Streams Simultaneously

### ISSUE THREAD

**Issue by vmohan7** [Unity-Technologies/UnityRenderStreaming#599] opened 2021-11-29 17:21 UTC
**Describe the bug**
Using 3.1.0-exp-2 (or more specifically latest version of develop), I have been trying to implement a BiDirectional Audio Feed. I am able to singularly send audio from Unity to the browser and using navigator.mediaDevices.getUserMedia({ audio : true }) I am able to receive audio from the Browser and hear it inside Unity. 

However, when I try to do both, neither audio stream is working, which suggests there is some sort of conflict happening between the sender and receiver code. 

**To Reproduce**
- On the web client, you need to create a navigator.mediaDevices.getUserMedia({ audio : true }) and audio track that should be sent to Unity.
- Setup an AudioReceiver and AudioSender on the Broadcaster
- When offer is received, setReceiver and AddSender

I have a sample of this working in the FusedVR Sample Project (0.7.0) branch in case that is helpful to reproduce. 

**Expected behavior**

Support for Audio Receiver and Audio Sender to work simultaneously. 

**Environment (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Unity Version 2019.4
 - Package version 3.0.1-exp-2

**Comment by karasusan** [comment] 2021-11-30 01:32
@vmohan7 
Hi, is it possible that the signaling process may become the cause of a bug?

**Comment by karasusan** [comment] 2021-11-30 05:11
memo: URS-345

**Comment by karasusan** [comment] 2021-11-30 05:13
@vmohan7 
We will update the bidirectional sample to add microphone audio input in the future.

**Comment by vmohan7** [comment] 2021-11-30 05:47
> @vmohan7 Hi, is it possible that the signaling process may become the cause of a bug?

Thanks for the reply. By signaling, do you mean from the client side? Currently on the client end, I do request a track for both the microphone and audio source. 

For the microphone:

```
    micStream = await navigator.mediaDevices.getUserMedia({ audio : true });
    audioMic = document.createElement('audio');
    audioMic.id = "mic";
    audioMic.srcObject = micStream;
    let micTrack = audioMic.srcObject.getTracks().find(x => x.kind == 'audio');
    newConnection.addMic(micTrack);
```

For the audio source, I use this on the Peer connection (addAudioStream is a function I added to add the Tranceiver for receiving that track)

```
  newConnection.addAudioStream(videoPlayers[0]); //add audio stream to just first video

  addAudioStream(videoPlayer) {
    this.pc.addTransceiver('audio', { direction: 'recvonly' });
    this.audioList.push(videoPlayer);
  }
```

In Unity, in the OnOffer function, I call `broadcast.AddSender(myConnection, source);` to add all my outgoing sources inlcuding audio

I also call `micStream?.SetReceiver(myConnection, rec); `which is the reciever I got from the OnAddReceiver callback. 

From Unity, if I either comment out SetReceiver or AddSender I am able to confirm that one of the Audio Streams can go through. In other words, without SetReceiver, I can play audio from Unity. Without AddSender, I can recieve the mic audio from the browser.

**Comment by vmohan7** [comment] 2021-12-02 05:43
@karasusan traced this back a little further and seems to be more related to the webrtc code. With both just a Receiver, the OnAudioReceive callback is triggered in the AudioStreamTrack. With both a sender and receiver, this OnAudioReceive callback is never called, but not sure why 

        [AOT.MonoPInvokeCallback(typeof(DelegateAudioReceive))]
        static void OnAudioReceive(

**Comment by karasusan** [comment] 2021-12-02 05:59
@vmohan7
Thanks for your effort. 
It could be good if there is the simplest sample for reproducing the issue.

**Comment by vmohan7** [comment] 2021-12-02 14:55
a bit difficult to wrap up since none of the samples have a microphone input, but let me see what I can do to help replicate

**Comment by burakkaraceylan** [comment] 2021-12-11 13:23
Can confirm:

I can send audio track from the browser (Chrome) to unity app (Android) just fine, but when I add Microphone Stream Sender to the Single Connection's streams list, the audio track from the unity app is sent to the browser and I can hear the audio on the browser, however then the audio track from the browser is not received. AudiStreamReceiver.OnUpdateReceiveAudioClip doesn't get called. 

Here are all the streams on the unity side:
![image](https://user-images.githubusercontent.com/84451726/145677993-cea859ad-1d55-400a-9fc2-45273b7b41f2.png)

Here you can find the signalling logs: https://0bin.net/paste/FKKR8tQv#xt6fbylydg7+1zTpZfw2YP6FaLg1NWZji98ZtXbUqnv

**Comment by karasusan** [comment] 2021-12-14 02:18
@burakkaraceylan
Thanks, it would be the bug in our side.

**Comment by burakkaraceylan** [comment] 2021-12-14 08:47
@karasusan 
Thank you for fast response to bug reports. Is there any temporary fix I can use until the next release? I am trying to get a POC ready asap.

**Comment by BonnyShen** [comment] 2021-12-14 10:06
@burakkaraceylan
I have met this problem yesterday. And I found something may fix this.

MicrophoneStreamSender.cs (line 35)
`            audioSource.clip = micClip;
            audioSource.loop = true;
            audioSource.Play();`

BidirectionalSample.cs (line 59)
`            receiveAudioViewer.OnUpdateReceiveAudioClip += clip =>
            {
                receiveAudioSource.clip = clip;
                receiveAudioSource.loop = true;
                receiveAudioSource.Play();
            };`

If the 'audioSource' target you assigned are the same. They may have conflicts.  
You can comment the code in MicrophoneStreamSender.cs if you dont want to listen the local clip. 
Or you can assign different 'audioSource' target.

**Comment by burakkaraceylan** [comment] 2021-12-15 09:18
Thank you @BonnyShen! That seems to be working. I will continute testing and share if any other problem occurs. Maybe @karasusan can assess whether this is a sufficient fix for now.

**Comment by karasusan** [comment] 2021-12-16 00:16
@burakkaraceylan @BonnyShen
I think this issue caused by the direction of transceiver, and need more time for fixing.

**Comment by karasusan** [comment] 2022-02-09 11:59
Merged #634

**Comment by karasusan** [comment] 2022-03-01 02:28
@vmohan7
Please check the new version **3.1.0-exp.3**.

**Closed** 2022-03-04 01:43 UTC
Labels: bug, waiting for release, issued

**Comment by vmohan7** [comment] 2022-03-04 21:44
@karasusan just tested. so doesn't work out of the box, but if I apply @BonnyShen recommendation and change the AddSenderTrack from SendOnly to SendRecv ([this line](https://github.com/Unity-Technologies/UnityRenderStreaming/blob/278e525170da39f07132f36d88a3149b1652dd32/com.unity.renderstreaming/Runtime/Scripts/RenderStreamingInternal.cs#L233
)) then it starts working for bi directional sending and receiving. 

Would you want me to file a separate issue for this?
