### ISSUE TITLE
[BUG] Incorrect mouse position in full-screen web player sample

### ISSUE THREAD

**Issue by ZeoWorks** [Unity-Technologies/UnityRenderStreaming#454] opened 2021-03-24 22:32 UTC
Hello again, hope you all are doing well. :)

There is an issue with the web video player sample upon entering full screen.
When you maximize the stream, the mouse position no longer syncs correctly to the renderstreaming IInput.

This was not an issue in 2.x.

1. Run the webserver and the unity webserver example scene,
2. Connect to the stream via videoplayer/index.html and go into full screen mode,
3. Mouse Input position is no longer correct.

**Comment by krisrok** [comment] 2021-07-15 12:12
I've a similar issue but even without entering fullscreen. I used the WebBrowserInput scene + Videoplayer Sample website.

Tested in Chrome, Firefox and Edge all produce the same offset in the non-fullscreen mode. In fullscreen the offset is exacerbated.

**Comment by karasusan** [comment] 2021-11-22 06:00
Hi, we fixed the mouse position when controlling it on browser.
https://github.com/Unity-Technologies/UnityRenderStreaming/pull/586

**Comment by karasusan** [comment] 2021-11-22 06:01
memo: URS-366

**Comment by zhanghaifei1997** [comment] 2021-12-10 03:10
Hello, when I was running unity-demo, the same problem as you (fix: Fix position of mouse pointer on browser #586) appeared. Is there a solution?

**Comment by karasusan** [comment] 2021-12-14 02:58
@zhanghaifei1997 

Hi, this issue has not solved yet.
I noticed that we should set two resolutions same.
![image](https://user-images.githubusercontent.com/1132081/145924879-20eada9b-2458-41d4-b7e4-3202cd9e11c6.png)

**Comment by zhanghaifei1997** [comment] 2021-12-14 03:12
> @zhanghaifei1997
> 
> Hi, this issue has not been solved yet. I noticed that we should set two resolutions same. ![image](https://user-images.githubusercontent.com/1132081/145924879-20eada9b-2458-41d4-b7e4-3202cd9e11c6.png)

Because I saw that you have provided a recorded video (mousepointer.mp4) at the top. The mouse click is normal in the video. How is that done?

**Comment by zhanghaifei1997** [comment] 2021-12-14 03:13
@karasusan Because I saw that you have provided a recorded video (mousepointer.mp4) at the top. The mouse click is normal in the video. How is that done?

**Comment by gotanidea** [comment] 2022-01-12 06:28
Yes, this problem hasn't been fixed yet.

**Comment by karasusan** [comment] 2022-02-09 12:01
This pull request fixes this issue. #589

**Comment by ByeTragedy** [comment] 2022-03-25 10:00
Can this fixed method be used on web only through "Broadcast" demo ?

**Comment by karasusan** [comment] 2022-03-29 02:40
@ByeTragedy
Not fixed yet.

**Comment by alikanat001** [comment] 2022-05-19 08:35
Considering this issue is not fixed, we were thinking of a applying synchronization ourselves. We thought of sending aspect ratio of both devices to each other as a text message and synchronize the cursor position accordingly. 

However, **RenderStreamingInternal** class is the only place we found that uses **PeerConnection** and **RTCDataChannel** but it is pretty much abstracted. So my question is is there a way we can use Unity.WebRtc and Unity.RenderStreaming in pair. Can we use Unity.WebRtc features such as sending aspect ratio of the device as a text message along with Unity.RenderStreaming streams and connections?

**Comment by kannan-xiao4** [comment] 2022-05-24 02:35
@alikanat001 
Currently, we cannot provide API for that issue.
We think it's better to expose `com.unity.webrtc` class on `RenderstreamingInternal`, and only plan it.
memo : URS-447

Cound you make a new issue with your feature request?

**Comment by karasusan** [comment] 2022-07-13 06:49
memo: URS-472

**Comment by Rhanjie** [comment] 2022-10-26 11:58
Hi. Is there any news about this issue?

I used before old version 1.2 but I decided to upgrade the module and also found this problem.

The first connected client has correctly synchronized touches. But if I set fullscreen or change the screen orientation, the issue with incorrect touch position appears. It's not just a small offset but a large difference. Second connected client (from another device) has always the problem. I have to restart the application and connect only second client if i want synchronized touches for him...

I also tested template project from docs with broadcast example but the issue is still here. Is there any solution or I should use any earlier version?

**Comment by karasusan** [comment] 2022-10-27 06:54
@Rhanjie
Thank you for sharing the detail. This issus is prioritized for us and we will fix it next version.

**Comment by yslab1** [comment] 2022-10-27 11:04
@karasusan We also have the same problem as @Rhanjie. When it be possible to fix it? This blocks the launch of our project.

**Comment by Rhanjie** [comment] 2022-10-28 12:08
I cloned the repo and tested the fix in your branch but unfortunately it didn't help. I recorded a short movie to better demonstrate the problem. Maybe it will be useful for you: https://youtu.be/4D61q_Dd4GU

In short. Every screen modification do not update the touch area correctly. Additionally, the UI Controller component that displays the red dot doesn't work good with touch gestures as you can see in the movie. Y position is always 0 for some reason and X has weird offset but the UI elements respond normally. It's just a problem with UI Controller.

I tested new version with previous webserver because the new one from exp.4 has problem described here: #795

**Comment by karasusan** [comment] 2022-10-31 01:28
@Rhanjie
Ah, I haven't checked the browser sample.  I am checking it.

**Comment by karasusan** [comment] 2022-10-31 10:25
@Rhanjie
Updated the PR. Could you check it?

**Comment by karasusan** [comment] 2022-11-01 08:34
Merged the #800 into develop branch.

**Comment by Rhanjie** [comment] 2022-11-01 16:54
I tested the merged version but still I can see the problem, nothing changed. Is it possible to work incorrectly because I have the previous version of webserver? The current one that I downloaded has problem with missing js files. Could you please update it?

**Comment by karasusan** [comment] 2022-11-02 02:19
@Rhanjie
I fixed the logic in web client so you need to use the latest version of webserver.

**Comment by Rhanjie** [comment] 2022-11-02 11:01
@karasusan 
Thank you for the information. I built new webserver and now the problem is fixed! Mouse and touch position are updated correctly even in mobile. 🎉

Unfortunately, with longer testing I found two other problems. There is still problem when the other client connects to active stream. Either it does not detect touch gestures at all or it is blocked for some reason. After refreshing the website the new client has restored ability to control the application but the first one loses it. The problem is even if I use two separated devices like PC and mobile phone.

In addition, there is a slight offset in the detected position, which is not very problematic, but makes it a little difficult to use the application. The problem occurs when a second client takes the application focus. Before this situation, the position is ok.

I presented the problem in the video below:
https://www.youtube.com/watch?v=rFifZz6fXkI

**Comment by karasusan** [comment] 2022-11-03 09:57
@Rhanjie
I haven't assumed that the use-case which multiple users control one camera. The `InputReceiver` class is designed for controlling input by single player.
I would like to make another ticket for fixing your issue. That will be alright won't it?

**Comment by Rhanjie** [comment] 2022-11-03 12:09
Of course, I will wait patiently for the next updates. Thank you for fast reaction and I really appreciate your work. The most important thing is that the main problem with the incorrect position is now fixed so I can go forward with my application. 😄 

Should I create the new issue for this problem?

**Comment by karasusan** [comment] 2023-01-17 02:39
We fixed this issue for the next version, but we still have an issue sometimes. We are checking it.

**Closed** 2023-02-28 02:41 UTC
Labels: bug, waiting for release, issued
